version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_db
    ports:
      - "8189:5432"
    networks:
      - appnet
  backend:
    build: plbcnr/deploy-automatizado:latest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=crud_db
    ports:
      - "8188:3000"
    depends_on:
      - db
    networks:
      - appnet
networks:
  appnet:
    driver: bridge